services:
  llm-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: llm-server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #count: 1
              capabilities: [gpu]
              device_ids: ['0']
    environment:
      - HF_HOME=/huggingface_cache
      - HUGGING_FACE_HUB_TOKEN=<YOUR_HUGGING_FACE_HUB_TOKEN>
    volumes:
      - /home/belletti/huggingface_cache:/huggingface_cache
      - /home/belletti/STE-model-calling/STE:/home/belletti/STE-model-calling/STE
    ports:
      - "8000:8000"

  llm-main:
    build:
      context: .
      dockerfile: Dockerfile.main
    container_name: llm-main
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #count: 1
              capabilities: [gpu]
              device_ids: ['0']
    environment:
      - HF_HOME=/huggingface_cache
      - HUGGING_FACE_HUB_TOKEN=<YOUR_HUGGING_FACE_HUB_TOKEN>
      - MODEL_CKPT=meta-llama/Meta-Llama-3-8B-Instruct
      - NUM_EPISODES=2
      - NUM_STM_SLOTS=1
      - MAX_TURN=3
      - MODEL_SERVER_URL=http://llm-server:8000/generate
    volumes:
      - /home/belletti/STE-model-calling/STE:/home/belletti/STE-model-calling/STE
      - /home/belletti/huggingface_cache:/huggingface_cache
    depends_on:
      - llm-server